---
- name: service | mariadb | started
  service:
    name: mariadb
    state: started

- name: service | mariadb | stopped
  service:
    name: mariadb
    state: stopped

- name: service | mariadb | restarted
  service:
    name: mariadb
    state: restarted
